FROM registry.access.redhat.com/ubi9/python-312 AS builder

USER 0
WORKDIR /build

RUN dnf install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf install -y \
    gcc \
    python3-devel && \
    dnf clean all

COPY pyproject.toml ./
COPY src/ src/
RUN pip install --no-cache-dir --prefix=/install .

FROM registry.access.redhat.com/ubi9/python-312

USER 0

RUN ARCH=$(uname -m) && \
    dnf install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    -o /etc/pki/rpm-gpg/RPM-GPG-KEY-ros2 && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-ros2 && \
    dnf config-manager --add-repo \
    "https://packages.ros.org/ros2/rhel/9/${ARCH}/" && \
    dnf install -y \
    ros-jazzy-rclpy \
    ros-jazzy-sensor-msgs \
    ros-jazzy-simulation-interfaces && \
    dnf clean all

COPY --from=builder /install /usr/local
COPY src/ /app/src/

WORKDIR /app
EXPOSE 8000 9876 9090

ENV PLAYGROUND_CONFIG=/etc/robotics-playground/config.yaml

USER 1001

CMD ["uvicorn", "robotics_playground.main:app", "--host", "0.0.0.0", "--port", "8000"]
