apiVersion: v1
kind: Service
metadata:
  name: fastdds-discovery
  labels:
    app.kubernetes.io/name: fastdds-discovery
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: robotics-playground
spec:
  selector:
    app.kubernetes.io/name: fastdds-discovery
  ports:
    - name: discovery
      port: 11811
      targetPort: discovery
      protocol: UDP
