apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service-zenoh.yaml

configMapGenerator:
  - name: zenoh-isaac-lab-config
    files:
      - config.json5=zenoh-config.json5
    options:
      disableNameSuffixHash: true
