services:
  ui:
    image: robotics-playground-ui:${TAG:-local}
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: robotics-playground:${TAG:-local}
    ports:
      - "8000:8000"
