services:
  ui:
    image: robotics-playground-ui:local
    build:
      context: ../frontend
      dockerfile: Containerfile
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: robotics-playground:local
    build:
      context: ../backend
      dockerfile: Containerfile
    ports:
      - "8000:8000"
