apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

configMapGenerator:
  - name: zenoh-backend-config
    files:
      - config.json5=zenoh-backend-config.json5
    options:
      disableNameSuffixHash: true
