apiVersion: v1
kind: Service
metadata:
  name: robotics-playground
  labels:
    app.kubernetes.io/name: robotics-playground
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: robotics-playground
spec:
  selector:
    app.kubernetes.io/name: robotics-playground
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: rerun-grpc
      port: 9876
      targetPort: rerun-grpc
      protocol: TCP
